[project]
name = "cnn"
version = "3.1.1"
description = "CNN"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "einops>=0.8.0",
    "numpy>=1.24.4",
    "torch>=2.0.0",
    "torchgeometry>=0.1.2",
]

[project.optional-dependencies]
dev = [
    "mypy>=1.11.2",
    "poethepoet>=0.28.0",
    "pydoclint>=0.5.7",
    "pytest-cov>=5.0.0",
    "ruff>=0.6.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = ["CPY001"]
fixable = ["ALL"]
unfixable = []
exclude = [".git", ".ruff_cache", ".venv",]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
preview = true

[tool.ruff.lint.isort]
known-first-party = ["cnn"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pydoclint]
style = 'numpy'
exclude = '\.git|\.ruff_cache|\.mypy_cache|\.venv'

[tool.poe.tasks]
lint-ruff = "ruff check --fix ."
lint-mypy = "mypy --strict ."
lint-pydoclint = "pydoclint ."
lint = ["lint-ruff", "lint-pydoclint", "lint-mypy",]
test = "pytest . --doctest-modules -ra --cov=src --cov-report=term --cov-report=xml"
