model:
  _target_: cnn.module.VAE
  testparams:
    _target_: cnn.module.TestParams
    v1: 1
    v2: 2

datamodule:
  _target_: cnn.datamodule.CNNDataModule
  data_name: pinpad_observation
  batch_size: 512
  num_workers: 4
  transforms:
    _target_: torchvision.transforms.Compose
    transforms:
      -
        _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1

trainer:
  _target_: lightning.Trainer
  accelerator: gpu
  devices:
    - 1
  max_epochs: 100
  gradient_clip_val: 10
  deterministic: true
  precision: 16-mixed
  log_every_n_steps: 1

callbacks:
  -
    _target_: cnn.callbacks.RichProgressBar
  -
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 100
    verbose: true
  -
    _target_: cnn.callbacks.LogCNNOutput
    every_n_epochs: 50
    indices:
      - 0
      - 49
      - 50
      - 99
      - 100
      - 149
      - 150
      - 199
      - 1000
      - 1049
      - 1050
      - 1099
      - 1100
      - 1145
      - 1150
      - 1195
