model:
  _target_: cnn.module.CategoricalAE
  class_size: 8
  category_size: 8
  encoder_config:
    _target_: cnn.network.EncoderConfig
    linear_sizes:
      _target_: builtins.tuple
      _args_:
        - [512, 64]
    activation_name: ELU
    out_activation_name: Identity
    channels:
      _target_: builtins.tuple
      _args_:
        - [16, 32, 64]
    kernel_sizes:
      _target_: builtins.tuple
      _args_:
        - [3, 3, 3]
    strides:
      _target_: builtins.tuple
      _args_:
        - [2, 2, 2]
    paddings:
      _target_: builtins.tuple
      _args_:
        - [1, 1, 1]
    observation_shape:
      _target_: builtins.tuple
      _args_:
        - [3, 64, 64]
  decoder_config:
    _target_: cnn.network.DecoderConfig
    linear_sizes:
      _target_: builtins.tuple
      _args_:
        - [64, 512]
    activation_name: ELU
    out_activation_name: Sigmoid
    channels:
      _target_: builtins.tuple
      _args_:
        - [64, 32, 16]
    kernel_sizes:
      _target_: builtins.tuple
      _args_:
        - [4, 4, 4]
    strides:
      _target_: builtins.tuple
      _args_:
        - [2, 2, 2]
    paddings:
      _target_: builtins.tuple
      _args_:
        - [1, 1, 1]
    output_paddings:
      _target_: builtins.tuple
      _args_:
        - [0, 0, 0]
    observation_shape:
      _target_: builtins.tuple
      _args_:
        - [3, 64, 64]

datamodule:
  _target_: cnn.datamodule.CNNDataModule
  data_name: pinpad_observation
  batch_size: 1024
  num_workers: 4
  transforms:
    _target_: torchvision.transforms.Compose
    transforms:
      -
        _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1

trainer:
  _target_: lightning.Trainer
  accelerator: gpu
  devices:
    - 2 
  max_epochs: -1
  gradient_clip_val: 10
  deterministic: true
  precision: 16-mixed
  log_every_n_steps: 1

callbacks:
  -
    _target_: cnn.callbacks.RichProgressBar
  -
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 100
    verbose: true
  -
    _target_: cnn.callbacks.LogCNNOutput
    every_n_epochs: 50
    indices:
      - 0
      - 49
      - 50
      - 99
      - 100
      - 149
      - 150
      - 199
      - 1000
      - 1049
      - 1050
      - 1099
      - 1100
      - 1145
      - 1150
      - 1195
