model:
  _target_: cnn.module.VAE
  encoder:
    _target_: cnn.network.Encoder
    linear_sizes:
      - 512
      - 256
    activation_name: ELU
    out_activation_name: Identity
    channels:
      - 16
      - 32
      - 64
    kernel_sizes:
      - 3
      - 3
      - 3
    strides:
      - 2
      - 2
      - 2
    paddings:
      - 1
      - 1
      - 1
    observation_shape:
      - 3
      - 64
      - 64

  decoder:
    _target_: cnn.network.Decoder
    linear_sizes:
      - 128
      - 512
    activation_name: ELU
    out_activation_name: Sigmoid
    channels:
      - 64
      - 32
      - 16
    kernel_sizes:
      - 4
      - 4
      - 4
    strides:
      - 2
      - 2
      - 2
    paddings:
      - 1
      - 1
      - 1
    output_paddings:
      - 0
      - 0
      - 0
    observation_shape:
      - 3
      - 64
      - 64

datamodule:
  _target_: cnn.datamodule.CNNDataModule
  data_name: pinpad_observation
  batch_size: 512
  num_workers: 4
  transforms:
    _target_: torchvision.transforms.Compose
    transforms:
      -
        _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1

trainer:
  _target_: lightning.Trainer
  accelerator: gpu
  devices:
    - 1
  max_epochs: 5000
  gradient_clip_val: 10
  deterministic: true
  precision: 16-mixed
  log_every_n_steps: 1

callbacks:
  -
    _target_: cnn.callbacks.RichProgressBar
  -
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_loss
    patience: 500
    verbose: true
  -
    _target_: cnn.callbacks.LogCNNOutput
    every_n_epochs: 50
    indices:
      - 0
      - 49
      - 50
      - 99
      - 100
      - 149
      - 150
      - 199
      - 1000
      - 1049
      - 1050
      - 1099
      - 1100
      - 1145
      - 1150
      - 1195
