name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up rye
        uses: sksat/setup-rye@v0.8.0
      - name: Install dependencies
        run: rye sync --no-lock
      - name: Run lint
        run: rye lint
      - name: Run test
        run: rye test
